# Generated by Django 3.2.25 on 2024-11-20 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_stagg',
            new_name='is_staff',
        ),
    ]
